name: Import AzureUpdates RSS FEED and JSON

on:
  schedule: 
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Import AzureUpdates Feed
        uses: robinkonrad/azureupdates2hugo-action@v1

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "azureupdates2hugo: Imported updated feed json & xml file"