name: Import AzureServices Updates

on:
  schedule: 
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_PAT }}


      - name: Import AzureUpdates Feed
        uses: robinkonrad/azureupdates2hugo-action@v1

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "azureupdates2hugo: Imported updated feed json & xml file"
          push_options: --force